import type { AuthoringApproach, AuthoringKind } from './draft.ts'

export type AuthoringLifecycleMap = {
  readonly workstreams?: readonly {
    readonly key: string
    readonly name: string
    readonly milestones?: readonly {
      readonly key: string
      readonly title: string
      readonly phases?: readonly {
        readonly key: string
        readonly title: string
        readonly plans?: readonly string[]
      }[]
    }[]
  }[]
}

export type GenerateAuthoringDesignSpecInput = {
  readonly title: string
  readonly kind: AuthoringKind
  readonly domain?: string
  readonly inspected_paths: readonly string[]
  readonly goal: string
  readonly constraints: readonly string[]
  readonly approaches: readonly AuthoringApproach[]
  readonly lifecycle: AuthoringLifecycleMap
  readonly roles: readonly string[]
  readonly tool_boundaries: readonly string[]
  readonly verification: readonly string[]
}

export type AuthoringDesignReview = {
  readonly ok: boolean
  readonly findings: readonly string[]
}

export type GenerateAuthoringDesignSpecResult = {
  readonly markdown: string
  readonly review: AuthoringDesignReview
  readonly approval: { readonly required: true; readonly status: 'pending' }
}

export function generateAuthoringDesignSpec(input: GenerateAuthoringDesignSpecInput): GenerateAuthoringDesignSpecResult {
  const recommendation = input.approaches.find((approach) => approach.recommended) ?? input.approaches[0]
  const lines: string[] = []

  lines.push(`# ${input.title}`)
  lines.push('')
  lines.push('> Generated by the Waypoint authoring wizard as a review draft. It is not an installed Quest, Recipe, operator, or route.')
  lines.push('')
  lines.push('## Current Context Inspected')
  for (const path of input.inspected_paths) lines.push(`- \`${path}\``)
  lines.push('')
  lines.push('## User Goal')
  lines.push(input.goal)
  lines.push('')
  lines.push('## Constraints and Non-goals')
  for (const constraint of input.constraints) lines.push(`- ${constraint}`)
  lines.push('- Do not generate installable manifests until the design is approved.')
  lines.push('')
  lines.push('## Approaches and Trade-offs')
  for (const approach of input.approaches) {
    lines.push(`### ${approach.recommended ? 'Recommended: ' : ''}${approach.title}`)
    lines.push(`slug: \`${approach.slug}\``)
    for (const tradeoff of approach.tradeoffs) lines.push(`- ${tradeoff}`)
    lines.push('')
  }
  lines.push('## Recommendation')
  lines.push(recommendation ? `${recommendation.title} (\`${recommendation.slug}\`)` : 'No recommendation available.')
  lines.push('')
  lines.push('## Lifecycle Map')
  for (const workstream of input.lifecycle.workstreams ?? []) {
    lines.push(`- workstream: \`${workstream.key}\` — ${workstream.name}`)
    for (const milestone of workstream.milestones ?? []) {
      lines.push(`  - milestone: \`${milestone.key}\` — ${milestone.title}`)
      for (const phase of milestone.phases ?? []) {
        lines.push(`    - phase: \`${phase.key}\` — ${phase.title}`)
        for (const plan of phase.plans ?? []) lines.push(`      - plan: \`${plan}\``)
      }
    }
  }
  if ((input.lifecycle.workstreams ?? []).length === 0) lines.push('- No lifecycle map supplied yet; capture this before implementation planning.')
  lines.push('')
  lines.push('## Roles and Operators')
  for (const role of input.roles) lines.push(`- ${role}`)
  lines.push('')
  lines.push('## Tool and Safety Boundaries')
  for (const boundary of input.tool_boundaries) lines.push(`- ${boundary}`)
  lines.push('')
  lines.push('## Verification Strategy')
  for (const command of input.verification) lines.push(`- \`${command}\``)
  lines.push('')
  lines.push('## Approval Status')
  lines.push('required: true')
  lines.push('status: pending')
  lines.push('blocked_next_steps: implementation_plan, quest_manifest, recipe_manifest, operator_manifest')
  lines.push('')

  const markdown = lines.join('\n')
  return { markdown, review: reviewAuthoringDesignSpec(markdown), approval: { required: true, status: 'pending' } }
}

export function reviewAuthoringDesignSpec(markdown: string): AuthoringDesignReview {
  const findings: string[] = []
  if (/\b(?:TODO|TBD)\b/i.test(markdown)) findings.push('spec contains TODO/TBD placeholders')
  if (!markdown.includes('## Approaches and Trade-offs') || !/^### /m.test(markdown)) {
    findings.push('spec must include at least two approaches and trade-offs')
  }
  const approachCount = (markdown.match(/^### /gm) ?? []).length
  if (approachCount > 0 && approachCount < 2) findings.push('spec must compare at least two approaches')
  if (!markdown.includes('## Recommendation')) findings.push('spec must include a recommendation')
  if (!markdown.includes('## Verification Strategy')) findings.push('spec must include verification strategy')
  if (/\binstall(?:ed|able)?\b/i.test(markdown) && !markdown.includes('not an installed')) {
    findings.push('spec has contradictory install/apply language')
  }
  return { ok: findings.length === 0, findings }
}
